import React, { useState, useEffect } from 'react';
import './AboutModal.css';

export default function AboutModal({ isOpen, onClose }) {
  const [hasAccepted, setHasAccepted] = useState(true);

  // Check initial gate state on mount
  useEffect(() => {
    const accepted = localStorage.getItem('diabetesAppDisclaimerAccepted');
    if (!accepted) {
      setHasAccepted(false);
    }
  }, []);

  // Force modal open if they haven't accepted the gate
  const showModal = isOpen || !hasAccepted;
  if (!showModal) return null;

  const isGate = !hasAccepted;

  const handleAccept = () => {
    localStorage.setItem('diabetesAppDisclaimerAccepted', 'true');
    setHasAccepted(true);
    if (!isOpen && onClose) onClose(); // Ensure external state syncs if needed
  };

  return (
    <div className="modal-overlay">
      <div className="modal-content">
        <div className="modal-header">
          <h2>{isGate ? 'Clinical Safety & Legal Notice' : 'About & Technology'}</h2>
          {!isGate && (
            <button className="close-btn" onClick={onClose} aria-label="Close">
              <svg viewBox="0 0 24 24"><path d="M18 6L6 18M6 6l12 12" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></svg>
            </button>
          )}
        </div>

        <div className="modal-scroll-area">
          <div className="modal-section alert-box">
            <h3>⚠️ Important Clinical Safety Notice & Medical Disclaimer</h3>
            <p><strong>1. For Educational Purposes Only</strong><br/>
              The Metabolic Risk & Remission Simulator is an advanced computational tool designed strictly for educational and informational purposes. It is not a medical device. The risk scores, XAI insights, and remission projections generated by this application do not constitute professional medical advice, diagnosis, or treatment.
            </p>
            <p><strong>2. Not a Substitute for a Doctor</strong><br/>
              Never disregard professional medical advice or delay in seeking it because of information provided by this application. Always consult with a qualified healthcare provider or physician regarding any medical condition, changes in your weight, or new symptoms (such as sudden weight loss, excessive thirst, or frequent urination).
            </p>
            <p><strong>3. Algorithmic Limitations</strong><br/>
              While this tool utilizes state-of-the-art Explainable AI (XGBoost) trained on clinical datasets, all machine learning models have a margin of error. The risk score is a statistical probability based on population data, not a definitive medical diagnosis.
            </p>
            <p><strong>4. The Remission Simulator (DiRECT Trial)</strong><br/>
              The Remission Simulator is based on data from the clinical DiRECT trial. However, significant weight loss is not clinically safe or indicated for everyone, particularly individuals with a normal or low BMI, or those with Type 1 Diabetes. Do not begin any restrictive diet or weight-loss program without medical supervision.
            </p>
          </div>

          {!isGate && (
            <>
              <div className="modal-section">
                <h3>About Us: Why We Built This</h3>
                <p><strong>The "Silent" Youth Epidemic</strong><br/>
                  Type 2 Diabetes (T2D) is undergoing a disturbing demographic shift. Once considered a condition primarily affecting older adults, diagnoses among people under 40 have risen by 40% in recent years. We are facing a "silent epidemic" where millions of young, working-age individuals are walking the line of metabolic dysfunction without knowing it.
                </p>
                <p>Traditional healthcare screening often relies on static questionnaires or requires immediate clinical blood tests, creating friction that delays early detection. We built this engine to bridge that gap, providing a frictionless, highly accurate, and instantly accessible digital triage tool designed for the modern era.</p>
                <p><strong>Shifting the Focus from Fear to Hope</strong><br/>
                  Historically, receiving a high diabetes risk score was a message of inevitable decline. We built this tool to challenge that narrative. By integrating the clinical outcomes of the landmark DiRECT trial into our Remission Simulator, our goal is to show that early-stage Type 2 Diabetes is not just preventable, but highly reversible. We don't just want to highlight your risk; we want to visualize your pathway to remission.
                </p>
              </div>

              <div className="modal-section">
                <h3>Our Technology: How We Do It</h3>
                <p><strong>1. Zero Data Egress (Absolute Privacy)</strong><br/>
                  Medical data is the most sensitive information you own. Standard health apps process your data by sending it to remote cloud servers, creating significant cybersecurity vulnerabilities. We engineered this application using a Client-Side Inference Architecture.
                </p>
                <p>What that means for you: When you click "Run Inference," your data never leaves your device. The entire AI model is downloaded locally to your browser. The calculations happen on your own smartphone or computer CPU. We do not track, store, or transmit a single piece of your health data.</p>
                <p><strong>2. Explainable AI (XAI)</strong><br/>
                  We refuse to use "Black Box" algorithms that spit out a scary number without context. Our engine utilizes SHAP (Shapley Additive Explanations) analysis. This means the AI doesn't just predict your risk; it mathematically breaks down exactly why it made that prediction, ranking the specific symptoms (like Polyuria or Polydipsia) that are driving your individual score. We believe algorithmic transparency is the foundation of patient trust.
                </p>
                <p><strong>3. Algorithmic Gatekeeping for Clinical Safety</strong><br/>
                  Technology should do no harm. While our Remission Simulator demonstrates the power of weight loss in reversing T2D, we built strict anthropometric guardrails into the software. The system calculates your Body Mass Index (BMI) locally and actively restricts the Remission Simulator for individuals who are not overweight, preventing the dangerous recommendation of weight loss where it is clinically contraindicated.
                </p>
              </div>
            </>
          )}
        </div>

        {isGate ? (
          <div className="modal-footer">
            <button className="accept-btn" onClick={handleAccept}>
              I Understand & Agree
            </button>
          </div>
        ) : (
          <div className="modal-footer">
            <button className="close-action-btn" onClick={onClose}>
              Close Menu
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
